//    uniCenta oPOS  - Touch Friendly Point Of Sale
//    Copyright (c) 2009-2014 uniCenta & previous Openbravo POS works
//    http://www.unicenta.com
//
//    This file is part of uniCenta oPOS
//
//    uniCenta oPOS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//   uniCenta oPOS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with uniCenta oPOS.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.ticket;


import com.openbravo.pos.forms.AppLocal;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import java.util.Properties;
import java.util.Date;
import com.openbravo.beans.JCalendarDialog;
/**
 *
 * @author JG uniCenta
 */
public class TicketPropertiesEdit extends javax.swing.JDialog {
    Properties ticketProperties;
    public static final String DOCTYPE = "vrstaDokumenta";
    public static final String CASHDATE = "datumValute";
    public static final String SERVICEDATE = "datumStoritve";
    public static final String DELIVERYDATE = "datumDobave";
    public static final String REFERENCE = "referenca";
    /** Creates new form JTicketsBagSharedList */
    private TicketPropertiesEdit(java.awt.Frame parent, boolean modal,Properties prop) {
        super(parent, modal);
        ticketProperties = prop;
        initComponents();
        init();
    }
    /** Creates new form JTicketsBagSharedList */
    private TicketPropertiesEdit(java.awt.Dialog parent, boolean modal,Properties prop) {
        super(parent, modal);
        ticketProperties = prop;
        initComponents();
        init();
    }
    
    private void init()
    {
        if(ticketProperties.containsKey(DOCTYPE)){
            for(int i=0; i<jComboBox1.getItemCount(); i++){
                if(ticketProperties.getProperty(DOCTYPE).equals((String)jComboBox1.getItemAt(i)))
                    jComboBox1.setSelectedIndex(i);
            }
        }
        
        if(ticketProperties.containsKey(SERVICEDATE))
            jTextField1.setText(ticketProperties.getProperty(SERVICEDATE));
        
        if(ticketProperties.containsKey(DELIVERYDATE))
            jTextField2.setText(ticketProperties.getProperty(DELIVERYDATE));
        
        if(ticketProperties.containsKey(CASHDATE))
            jTextField3.setText(ticketProperties.getProperty(CASHDATE));
        
        if(ticketProperties.containsKey(REFERENCE))
            jTextField4.setText(ticketProperties.getProperty(REFERENCE));
    }
    /**
     *
     * @param parent
     * @param prop
     * @return
     */
    public static TicketPropertiesEdit newJDialog(Window parent, Properties prop) {
        
        Window window = getWindow(parent);
        TicketPropertiesEdit mydialog;
        if (window instanceof Frame) { 
            mydialog = new TicketPropertiesEdit((Frame) window, true, prop);
        } else {
            mydialog = new TicketPropertiesEdit((Dialog) window, true, prop);
        } 
        return mydialog;
    }
    
    private static Window getWindow(Component parent) {
        if (parent == null) {
            return new JFrame();
        } else if (parent instanceof Frame || parent instanceof Dialog) {
            return (Window) parent;
        } else {
            return getWindow(parent.getParent());
        }
    }  


    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        m_jButtonCancel = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        setTitle(AppLocal.getIntString("caption.ticketproperties")); // NOI18N

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        jPanel3.add(jPanel4);

        m_jButtonCancel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        m_jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/ok.png"))); // NOI18N
        m_jButtonCancel.setText(AppLocal.getIntString("Button.OK")); // NOI18N
        m_jButtonCancel.setFocusPainted(false);
        m_jButtonCancel.setFocusable(false);
        m_jButtonCancel.setMargin(new java.awt.Insets(8, 16, 8, 16));
        m_jButtonCancel.setRequestFocusEnabled(false);
        m_jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jButtonOkActionPerformed(evt);
            }
        });
        jPanel3.add(m_jButtonCancel);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel1.setMinimumSize(new java.awt.Dimension(350, 34));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Informativni predračun", "Predračun", "Oddajnica", "Obrnjena stopnja DDV" }));
        jPanel1.add(jComboBox1);

        jPanel6.add(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 40));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        jLabel2.setText("Datum storitve");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanel2.add(jLabel2);

        jTextField1.setEditable(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel2.add(jTextField1);

        jButton4.setToolTipText("");
        jButton4.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/date.png"))); // NOI18N
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setPreferredSize(new java.awt.Dimension(38, 38));
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jPanel6.add(jPanel2);

        jPanel7.setPreferredSize(new java.awt.Dimension(300, 40));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout2.setAlignOnBaseline(true);
        jPanel7.setLayout(flowLayout2);

        jLabel3.setText("Datum dobave");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanel7.add(jLabel3);

        jTextField2.setEditable(false);
        jTextField2.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel7.add(jTextField2);

        jButton5.setToolTipText("");
        jButton5.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/date.png"))); // NOI18N
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.setPreferredSize(new java.awt.Dimension(38, 38));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        jPanel6.add(jPanel7);

        jPanel8.setPreferredSize(new java.awt.Dimension(300, 40));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout3.setAlignOnBaseline(true);
        jPanel8.setLayout(flowLayout3);

        jLabel4.setText("Datum valute");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanel8.add(jLabel4);

        jTextField3.setEditable(false);
        jTextField3.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel8.add(jTextField3);

        jButton6.setToolTipText("");
        jButton6.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton6);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/date.png"))); // NOI18N
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.setPreferredSize(new java.awt.Dimension(38, 38));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3);

        jPanel6.add(jPanel8);

        jPanel9.setPreferredSize(new java.awt.Dimension(300, 40));
        java.awt.FlowLayout flowLayout5 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout5.setAlignOnBaseline(true);
        jPanel9.setLayout(flowLayout5);

        jLabel5.setText("Referenca");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanel9.add(jLabel5);

        jTextField4.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel9.add(jTextField4);

        jPanel6.add(jPanel9);

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(313, 335));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void m_jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jButtonOkActionPerformed

        ticketProperties.setProperty(DOCTYPE, (String)jComboBox1.getSelectedItem());
        
        if(jTextField1.getText().length()>2)
            ticketProperties.setProperty(SERVICEDATE, jTextField1.getText());
        
        if(jTextField2.getText().length()>2)
            ticketProperties.setProperty(DELIVERYDATE, jTextField2.getText());
        
        if(jTextField3.getText().length()>2)
            ticketProperties.setProperty(CASHDATE, jTextField3.getText());
        
        if(jTextField4.getText().length()>2)
            ticketProperties.setProperty(REFERENCE, jTextField4.getText());
   
        dispose();
        
    }//GEN-LAST:event_m_jButtonOkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date d = new Date();
        JCalendarDialog.showCalendar(jButton1, d);
        jTextField1.setText(d.toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField1.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextField2.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextField3.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Date d = new Date();
        JCalendarDialog.showCalendar(jButton2, d);
        jTextField2.setText(d.toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Date d = new Date();
        JCalendarDialog.showCalendar(jButton3, d);
        jTextField3.setText(d.toString());
    }//GEN-LAST:event_jButton3ActionPerformed
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton m_jButtonCancel;
    // End of variables declaration//GEN-END:variables
    
}
